### ISSUE TITLE
App crashes as soon as there are settings. only apn_clear works

### ISSUE THREAD

**Issue by theoneandonly-vector** [h-mdm/hmdm-plugin-apn#2]
old issue -> changed

**Comment by h-mdm** [comment]
The message "Please install APN setup helper through Headwind MDM" is shown when the app cannot connect to Headwind MDM. If the device is running Headwind MDM, I can only guess that you have changed the package ID of Headwind MDM.

**Comment by theoneandonly-vector** [comment]
I just switched back to no modifications and only changed "signingConfigs" to match my key. But as soon as I apply Applications Settings to it the app crashes on launch.

**Comment by theoneandonly-vector** [comment]
App crashes as soon as there are settings. only apn_clear / no settings look like t works.
as soon as I have settings applied through hmdm -> it crashes.

**Comment by theoneandonly-vector** [comment]
any way to debug?

**Comment by h-mdm** [comment]
APN can be changed only on Android 9 and above. On which Android version do you run the app?

**Comment by theoneandonly-vector** [comment]
Android 9

**Comment by h-mdm** [comment]
I kindly ask you to run logcat on the device (https://developer.android.com/studio/command-line/logcat), find the crash report (it will be a stack trace), and paste the full stack trace here. This will help to fix the issue.

**Comment by theoneandonly-vector** [comment]
hey there, can you tell me how to limit my logs to only relevant info?

here is a truncated version:
```
11-24 15:00:21.692   420   603 I BufferQueueProducer: [com.hmdm.launcher/com.hmdm.launcher.ui.MainActivity#0](this:0x7d6a650800,id:36,api:1,p:1830,c:420) disconnect(P): api 1
11-24 15:00:21.706   420   420 I BufferQueueConsumer: [com.hmdm.launcher/com.hmdm.launcher.ui.MainActivity#0](this:0x7d6a650800,id:36,api:1,p:-1,c:-1) disconnect(C)
11-24 15:00:21.811   420   420 I BufferQueueConsumer: [StatusBar#0](this:0x7d7259e800,id:3,api:1,p:1099,c:420) setDefaultBufferSize: width=1080 height=1920
11-24 15:00:21.819   420  1037 I BufferQueueProducer: [StatusBar#0](this:0x7d7259e800,id:3,api:1,p:1099,c:420) disconnect(P): api 1
11-24 15:00:21.820   420  1037 I BufferQueueProducer: [StatusBar#0](this:0x7d7259e800,id:3,api:1,p:1099,c:420) connect(P): api=1 producer=(1099:com.android.systemui) producerControlledByApp=true
11-24 15:00:21.834  1099  1099 W View    : requestLayout() improperly called by com.android.keyguard.CarrierText{59f8b0c V.ED..... ......ID 48,0-810,120 #7f0a0193 app:id/keyguard_carrier_text} during layout: running second layout pass
11-24 15:00:21.886   420   441 I BufferQueueProducer: [StatusBar#0](this:0x7d7259e800,id:3,api:1,p:1099,c:420) queueBuffer: fps=0.20 dur=4957.30 max=4957.30 min=4957.30
11-24 15:00:21.892   420   441 W SurfaceFlinger: Attempting to set client state on removed layer: Dim Layer for - mAboveAppWindowsContainers#0
11-24 15:00:21.892   420   441 W SurfaceFlinger: Attempting to destroy on removed layer: Dim Layer for - mAboveAppWindowsContainers#0
11-24 15:00:22.295   956  3788 I ActivityManager: Killing 6660:com.hmdm.apn/u0a102 (adj 900): crash
11-24 15:00:22.299  1099  1099 I vol.Events: writeEvent dismiss_dialog volume_controller
11-24 15:00:22.303   956   975 W libprocessgroup: kill(-6660, 9) failed: No such process
11-24 15:00:22.303   956   975 I libprocessgroup: Successfully killed process cgroup uid 10102 pid 6660 in 0ms
11-24 15:00:22.314   420   441 I BufferQueueProducer: [Application Error: com.hmdm.apn#0](this:0x7d7259d000,id:38,api:1,p:956,c:420) disconnect(P): api 1
11-24 15:00:22.322   420  1037 W SurfaceFlinger: Attempting to destroy on removed layer: fbf7683 Application Error: com.hmdm.apn#0
11-24 15:00:22.323   420   420 I BufferQueueConsumer: [Application Error: com.hmdm.apn#0](this:0x7d7259d000,id:38,api:1,p:-1,c:-1) disconnect(C)
11-24 15:00:22.323   420   420 I BufferQueue: [Application Error: com.hmdm.apn#0](this:0x7d7259d000,id:38,api:1,p:-1,c:-1) ~BufferQueueCore
11-24 15:00:22.327   541   541 I Zygote  : Process 6660 exited due to signal (9)
11-24 15:00:22.330   956   982 W ActivityManager: setHasOverlayUi called on unknown pid: 6660
11-24 15:00:22.330   420  1037 I SurfaceFlinger: [SF client] Remove(0x7d728335c0) for (956:system_server)
11-24 15:00:24.589   578   578 I thermal_repeater: [recvMdThermalInfo] ret=37, strLen=127,  2, 32767, -127, 20821, 32767, -20554
11-24 15:00:34.608   578   578 I thermal_repeater: [recvMdThermalInfo] ret=33, strLen=127,  2, 32767, -127, -27780, 32767, 0
11-24 15:00:39.325   956  1036 I DataShapingService: openLteGateSuccess = false
11-24 15:00:44.627   578   578 I thermal_repeater: [recvMdThermalInfo] ret=37, strLen=127,  2, 32767, -127, 20821, 32767, -20554
11-24 15:00:47.690  5668  5668 I ADB_SERVICES: fdevent_loop length=1
11-24 15:00:47.690  5668  5668 I ADB_SERVICES: service_to_fd shell:export ANDROID_LOG_TAGS="''"; exec logcat 'com.hmdm.apn'
11-24 15:00:47.727  5668  5668 I ADB_SERVICES: local_socket_flush_outgoing read_data=3859
11-24 15:00:52.266   956  1120 D AES     : AEEIOCTL_GET/SET_SF_STATE IOCTL,cmd= 1074294797, lParam=0.
11-24 15:00:52.267   956  1120 D AES     : AEEIOCTL_RT_MON_Kick IOCTL,cmd= 2147774474, lParam=300.
11-24 15:00:54.647   578   578 I thermal_repeater: [recvMdThermalInfo] ret=37, strLen=127,  2, 32767, -127, 20821, 32767, -20554
11-24 15:01:04.667   578   578 I thermal_repeater: [recvMdThermalInfo] ret=33, strLen=127,  2, 32767, -127, -27780, 32767, 0
11-24 15:01:07.016   956  1036 D DataShapingService: [isDataShapingWhitelistApp] packageName: android
11-24 15:01:07.016   956  1036 D DataShapingUtils: [isDataShapingWhitelistApp] packageName: android, mWhitelist: []
11-24 15:01:07.016   956  1036 D DataShapingService: [isDataShapingWhitelistApp] packageName: com.google.android.gms
11-24 15:01:07.016   956  1036 D DataShapingUtils: [isDataShapingWhitelistApp] packageName: com.google.android.gms, mWhitelist: []
11-24 15:01:07.017   956  1036 D DataShapingService: [isDataShapingWhitelistApp] packageName: com.google.android.gms
11-24 15:01:07.017   956  1036 D DataShapingUtils: [isDataShapingWhitelistApp] packageName: com.google.android.gms, mWhitelist: []
11-24 15:01:07.017   956  1036 D DataShapingService: [openLteDataUpLinkGate] isForce: false
11-24 15:01:07.017   956  1036 D DataShapingService: Alarm manager openLteDataUpLinkGate: false
11-24 15:01:07.017   956  1036 I DataShapingService: openLteGateSuccess = false
11-24 15:01:07.049   573  1025 I Accelerometer: batch: handle:0, flag:0,samplingPeriodNs:20000000 maxBatchReportLatencyNs:0
11-24 15:01:07.050   573  1025 I Accelerometer: enable: handle:0, en:1
11-24 15:01:07.068  6356  6720 I ChmraDebugLogger: [39] null
11-24 15:01:07.585   573  1025 I Accelerometer: enable: handle:0, en:0
1
```

**Comment by h-mdm** [comment]
You need to find an exception stack trace. The non-relevant information will not help to fix the issue. You can use the command
adb logcat > logcat.txt
and after getting logs, search for Exception or something like that.

**Comment by theoneandonly-vector** [comment]
is it maybe this "GmsIntentOperationService"?
```
11-24 14:51:37.101   956   967 W ActivityManager: Background start not allowed: service Intent { act=stop cmp=com.hmdm.launcher/.service.LocationService } to com.hmdm.launcher/.service.LocationService from pid=1830 uid=10102 pkg=com.hmdm.launcher startFg?=false
--------- beginning of crash
11-24 14:51:37.766  1676  2057 E AndroidRuntime: FATAL EXCEPTION: [com.google.android.gms.chimera.GmsIntentOperationService$ChimeraService-Executor] idle
11-24 14:51:37.766  1676  2057 E AndroidRuntime: Process: com.google.android.gms, PID: 1676
11-24 14:51:37.766  1676  2057 E AndroidRuntime: java.lang.IllegalArgumentException: Component class com.google.android.gms.setupservices.GoogleServicesActivity does not exist in com.google.android.gms
11-24 14:51:37.766  1676  2057 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:1954)
11-24 14:51:37.766  1676  2057 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1918)
11-24 14:51:37.766  1676  2057 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1868)
11-24 14:51:37.766  1676  2057 E AndroidRuntime: 	at android.content.pm.IPackageManager$Stub$Proxy.setComponentEnabledSetting(IPackageManager.java:4892)
11-24 14:51:37.766  1676  2057 E AndroidRuntime: 	at android.app.ApplicationPackageManager.setComponentEnabledSetting(ApplicationPackageManager.java:2319)
11-24 14:51:37.766  1676  2057 E AndroidRuntime: 	at crr.a(:com.google.android.gms.policy_sidecar_aps@2757081@2757081.261727253.261727253:34)
11-24 14:51:37.766  1676  2057 E AndroidRuntime: 	at com.google.android.gms.setupservices.SetupServicesInitIntentOperation.a(:com.google.android.gms.policy_sidecar_aps@2757081@2757081.261727253.261727253:1)
11-24 14:51:37.766  1676  2057 E AndroidRuntime: 	at bvu.onHandleIntent(:com.google.android.gms.policy_sidecar_aps@2757081@2757081.261727253.261727253:7)
11-24 14:51:37.766  1676  2057 E AndroidRuntime: 	at com.google.android.chimera.IntentOperation.onHandleIntent(:com.google.android.gms@204217083@20.42.17 (080406-342117392):2)
11-24 14:51:37.766  1676  2057 E AndroidRuntime: 	at htw.onHandleIntent(:com.google.android.gms@204217083@20.42.17 (080406-342117392):6)
11-24 14:51:37.766  1676  2057 E AndroidRuntime: 	at buc.run(:com.google.android.gms@204217083@20.42.17 (080406-342117392):4)
11-24 14:51:37.766  1676  2057 E AndroidRuntime: 	at bub.run(:com.google.android.gms@204217083@20.42.17 (080406-342117392):13)
11-24 14:51:37.766  1676  2057 E AndroidRuntime: 	at aozh.run(:com.google.android.gms@204217083@20.42.17 (080406-342117392):2)
11-24 14:51:37.766  1676  2057 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
11-24 14:51:37.766  1676  2057 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
11-24 14:51:37.766  1676  2057 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:764)
11-24 14:51:37.766  1676  2057 E AndroidRuntime: Caused by: android.os.RemoteException: Remote stack trace:
11-24 14:51:37.766  1676  2057 E AndroidRuntime: 	at com.android.server.pm.PackageManagerService.setEnabledSetting(PackageManagerService.java:21156)
11-24 14:51:37.766  1676  2057 E AndroidRuntime: 	at com.android.server.pm.PackageManagerService.setComponentEnabledSetting(PackageManagerService.java:20927)
11-24 14:51:37.766  1676  2057 E AndroidRuntime: 	at android.content.pm.IPackageManager$Stub.onTransact(IPackageManager.java:1550)
11-24 14:51:37.766  1676  2057 E AndroidRuntime: 	at com.android.server.pm.PackageManagerService.onTransact(PackageManagerService.java:3966)
11-24 14:51:37.766  1676  2057 E AndroidRuntime: 	at android.os.Binder.execTransact(Binder.java:731)
```

**Comment by h-mdm** [comment]
Which application is crashed?

If it is the APN plugin, its package ID is com.hmdm.apn

You can try to search for an exception containing this package id.

**Comment by theoneandonly-vector** [comment]
```
11-24 14:57:41.069   956   972 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
11-24 14:57:41.070   956   972 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
11-24 14:57:41.104   956  5763 I ActivityManager: Process com.google.android.gms (pid 6305) has died: fore SVC 
11-24 14:57:41.105   956  5763 W ActivityManager: Scheduling restart of crashed service com.google.android.gms/.chimera.container.FileApkChimeraService$FileApkService in 5656ms
11-24 14:57:41.105   956  5763 W ActivityManager: Scheduling restart of crashed service com.google.android.gms/.chimera.GmsIntentOperationService in 45656ms
11-24 14:57:43.587   956   974 I ActivityManager: Start proc 6356:com.google.android.gms/u0a13 for content provider com.google.android.gms/.people.service.galprovider.PeopleGalProvider
11-24 14:57:43.629   956   956 W Looper  : Slow dispatch took 103ms main h=android.app.ActivityThread$H c=android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA@ac6c54d m=0
11-24 14:57:43.701   956   956 I Telecom : DefaultDialerCache: Refreshing default dialer for user 0: now com.android.dialer: DDC.oR@ADU
11-24 14:57:44.165  6356  6383 W PackageParser: Unknown element under <manifest>: queries at /data/user_de/0/com.google.android.gms/app_chimera/m/00000010/AdsDynamite.apk Binary XML file line #5
11-24 14:57:44.696  6356  6383 I chatty  : uid=10013(com.google.android.gms) identical 2 lines
11-24 14:57:44.931  6356  6383 W PackageParser: Unknown element under <manifest>: queries at /data/user_de/0/com.google.android.gms/app_chimera/m/00000010/AdsDynamite.apk Binary XML file line #5
11-24 14:58:00.001   956  1036 I DataShapingService: openLteGateSuccess = false
11-24 14:58:05.055   956  1036 I chatty  : uid=1000(system) AlarmManager identical 2 lines
11-24 14:58:06.407   956  1036 I DataShapingService: openLteGateSuccess = false
11-24 14:58:20.028   567   596 E storaged: getDiskStats failed with result NOT_SUPPORTED and size 0
11-24 14:58:35.562   956   988 E PackageManager: Adding duplicate user id: 10102 name=com.hmdm.apn
11-24 14:58:37.205   956   972 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_ADDED dat=package:com.hmdm.apn flg=0x4000010 (has extras) } to com.android.musicfx/.Compatibility$Receiver
11-24 14:58:37.206   956   972 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_ADDED dat=package:com.hmdm.apn flg=0x4000010 (has extras) } to com.android.vending/com.google.android.finsky.packagemanager.impl.PackageMonitorReceiverImpl$RegisteredReceiver
11-24 14:58:37.206   956   972 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_ADDED dat=package:com.hmdm.apn flg=0x4000010 (has extras) } to com.google.android.gms/.games.chimera.GamesSystemBroadcastReceiverProxy
11-24 14:58:37.207   956   972 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_ADDED dat=package:com.hmdm.apn flg=0x4000010 (has extras) } to com.google.android.gms/.gass.chimera.PackageChangeBroadcastReceiver
11-24 14:58:37.207   956   972 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_ADDED dat=package:com.hmdm.apn flg=0x4000010 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
11-24 14:58:37.207   956   972 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_ADDED dat=package:com.hmdm.apn flg=0x4000010 (has extras) } to com.google.android.googlequicksearchbox/com.google.android.apps.gsa.googlequicksearchbox.GelStubAppWatcher
11-24 14:58:37.217   956   972 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.PACKAGE_ADDED dat=package:com.hmdm.apn flg=0x4000010 (has extras) } to com.google.android.ims/.receivers.RcsAutoStartReceiver
11-24 14:58:37.299   956   956 W Looper  : Slow dispatch took 102ms main h=android.app.ActivityThread$H c=android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA@2e15566 m=0
11-24 14:58:37.437   956   956 W Looper  : Slow dispatch took 134ms main h=android.app.ActivityThread$H c=android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA@cc51777 m=0
11-24 14:58:37.438   956   956 W Looper  : Slow delivery took 241ms main h=android.app.ActivityThread$H c=android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA@a1b6fe4 m=0
11-24 14:58:37.441   956   956 I Telecom : DefaultDialerCache: Refreshing default dialer for user 0: now com.android.dialer: DDC.oR@ADc
11-24 14:58:37.461   956   971 E AutofillManagerServiceImpl: Bad AutofillService name: com.google.android.gms/.autofill.service.AutofillService
11-24 14:58:37.461   956   971 E AutofillManagerServiceImpl: Bad AutofillService name: com.google.android.gms/.autofill.service.AutofillService
11-24 14:58:37.475   956  1321 W ActivityManager: Unable to start service Intent { act=com.google.android.gms.auth.key.retrieval.service.START pkg=com.google.android.gms } U=0: not found
11-24 14:58:37.476   956  1738 W ActivityManager: Unbind failed: could not find connection for android.os.BinderProxy@dc56d4e
11-24 14:58:37.543   956   956 W Looper  : Drained
11-24 14:58:39.325   956  1036 I DataShapingService: openLteGateSuccess = false
11-24 14:58:39.919   956  1516 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 pkg=com.ses.app.apkexport cmp=com.ses.app.apkexport/.Main} from uid 10102
11-24 14:58:39.975   956   974 I ActivityManager: Start proc 6505:com.ses.app.apkexport/u0a103 for activity com.ses.app.apkexport/.Main
11-24 14:58:40.009   956  1751 W ActivityManager: Request to remove task ignored for non-existent task 11
11-24 14:58:42.400   956  1738 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10000000 pkg=com.hmdm.apn cmp=com.hmdm.apn/.MainActivity} from uid 10102
11-24 14:58:42.452   956   974 I ActivityManager: Start proc 6554:com.hmdm.apn/u0a102 for activity com.hmdm.apn/.MainActivity
11-24 14:58:42.685  6554  6554 E AndroidRuntime: FATAL EXCEPTION: main
11-24 14:58:42.685  6554  6554 E AndroidRuntime: Process: com.hmdm.apn, PID: 6554
11-24 14:58:42.685  6554  6554 E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method getProxyAddressAsString()Ljava/lang/String; in class Landroid/telephony/data/ApnSetting; or its super classes (declaration of 'android.telephony.data.ApnSetting' appears in /system/framework/framework.jar!classes2.dex)
11-24 14:58:42.685  6554  6554 E AndroidRuntime: 	at com.hmdm.apn.MainActivity.reportSuccess(MainActivity.java:171)
11-24 14:58:42.685  6554  6554 E AndroidRuntime: 	at com.hmdm.apn.MainActivity.setupApns(MainActivity.java:219)
11-24 14:58:42.685  6554  6554 E AndroidRuntime: 	at com.hmdm.apn.MainActivity.loadSettings(MainActivity.java:98)
11-24 14:58:42.685  6554  6554 E AndroidRuntime: 	at com.hmdm.apn.MainActivity.onMDMConnected(MainActivity.java:237)
11-24 14:58:42.685  6554  6554 E AndroidRuntime: 	at com.hmdm.MDMService$RemoteServiceConnection.onServiceConnected(MDMService.java:93)
11-24 14:58:42.685  6554  6554 E AndroidRuntime: 	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1734)
11-24 14:58:42.685  6554  6554 E AndroidRuntime: 	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1766)
11-24 14:58:42.685  6554  6554 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
11-24 14:58:42.685  6554  6554 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-24 14:58:42.685  6554  6554 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
11-24 14:58:42.685  6554  6554 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6702)
11-24 14:58:42.685  6554  6554 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-24 14:58:42.685  6554  6554 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
11-24 14:58:42.685  6554  6554 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
11-24 14:58:42.690   956  1321 W ActivityManager:   Force finishing activity com.hmdm.apn/.MainActivity
11-24 14:58:42.700   956   972 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
11-24 14:58:42.704   956   973 I ActivityManager: Showing crash dialog for package com.hmdm.apn u0
11-24 14:58:42.704   956   972 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
11-24 14:58:42.794   956  3661 E AutofillManagerServiceImpl: Bad AutofillService name: com.google.android.gms/.autofill.service.AutofillService
11-24 14:58:42.913   956   973 W Looper  : Slow dispatch took 147ms android.ui h=android.view.Choreographer$FrameHandler c=android.view.Choreographer$FrameDisplayEventReceiver@9067989 m=0
11-24 14:58:43.193   956   972 W ActivityManager: Activity pause timeout for ActivityRecord{90bf688 u0 com.hmdm.apn/.MainActivity t13 f}
11-24 14:58:43.877   956  1321 W ActivityManager:   Force finishing activity com.hmdm.apn/.MainActivity
11-24 14:58:43.884   956  1321 I ActivityManager: Killing 6554:com.hmdm.apn/u0a102 (adj 900): crash
11-24 14:58:43.922   956   982 W ActivityManager: setHasOverlayUi called on unknown pid: 6554
11-24 14:58:46.414   956  1036 I DataShapingService: openLteGateSuccess = false
11-24 14:58:52.336   956  1036 I DataShapingService: openLteGateSuccess = false
11-24 14:58:56.536  6356  6392 W PackageParser: Unknown element under <manifest>: queries at /data/user_de/0/com.google.android.gms/app_chimera/m/00000010/AdsDynamite.apk Binary XML file line #5
11-24 14:59:00.003   956  1036 I DataShapingService: openLteGateSuccess = false
11-24 14:59:15.488   956  1040 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.HOME] flg=0x10200000 cmp=com.hmdm.launcher/.ui.MainActivity (has extras)} from uid 1000
11-24 14:59:15.552   956  1745 V SettingsProvider: name : screen_brightness_mode appId : 1000
11-24 14:59:15.553   956  1751 V SettingsProvider: name : screen_brightness appId : 1000
11-24 14:59:15.558   956  4226 V SettingsProvider: name : screen_off_timeout appId : 1000
11-24 14:59:16.725   956  4226 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 pkg=com.hmdm.apn cmp=com.hmdm.apn/.MainActivity} from uid 10102
11-24 14:59:16.769   956   972 I ActivityManager: Killing 2704:com.android.vending:download_service/u0a31 (adj 906): empty #17
11-24 14:59:16.792   956  3788 D MtkConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ LISTEN id=29, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Unwanted:  Uid: 10031] ], android.os.BinderProxy@5eb5c70)
11-24 14:59:16.792   956  1745 D MtkConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ TRACK_DEFAULT id=23, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Unwanted:  Uid: 10031] ], android.os.BinderProxy@d1deeb3)
11-24 14:59:16.794   956  1751 D MtkConnectivityService: ConnectivityService NetworkRequestInfo binderDied(NetworkRequest [ TRACK_DEFAULT id=28, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Unwanted:  Uid: 10031] ], android.os.BinderProxy@a00abe9)
11-24 14:59:16.796   956  1054 D MtkConnectivityService: releasing NetworkRequest [ TRACK_DEFAULT id=23, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Unwanted:  Uid: 10031] ] (release request)
11-24 14:59:16.798   956  1054 D MtkConnectivityService: releasing NetworkRequest [ TRACK_DEFAULT id=28, [ Capabilities: INTERNET&NOT_RESTRICTED&TRUSTED Unwanted:  Uid: 10031] ] (release request)
11-24 14:59:16.806   956   974 I ActivityManager: Start proc 6660:com.hmdm.apn/u0a102 for activity com.hmdm.apn/.MainActivity
11-24 14:59:16.873   956  1751 V SettingsProvider: packageValueForCallResult, name = null, value : Bundle[{_track_generation=android.util.MemoryIntArray@60, value=null, _generation_index=0, _generation=12}]
11-24 14:59:17.045  6660  6660 E AndroidRuntime: FATAL EXCEPTION: main
11-24 14:59:17.045  6660  6660 E AndroidRuntime: Process: com.hmdm.apn, PID: 6660
11-24 14:59:17.045  6660  6660 E AndroidRuntime: java.lang.NoSuchMethodError: No virtual method getProxyAddressAsString()Ljava/lang/String; in class Landroid/telephony/data/ApnSetting; or its super classes (declaration of 'android.telephony.data.ApnSetting' appears in /system/framework/framework.jar!classes2.dex)
11-24 14:59:17.045  6660  6660 E AndroidRuntime: 	at com.hmdm.apn.MainActivity.reportSuccess(MainActivity.java:171)
11-24 14:59:17.045  6660  6660 E AndroidRuntime: 	at com.hmdm.apn.MainActivity.setupApns(MainActivity.java:219)
11-24 14:59:17.045  6660  6660 E AndroidRuntime: 	at com.hmdm.apn.MainActivity.loadSettings(MainActivity.java:98)
11-24 14:59:17.045  6660  6660 E AndroidRuntime: 	at com.hmdm.apn.MainActivity.onMDMConnected(MainActivity.java:237)
11-24 14:59:17.045  6660  6660 E AndroidRuntime: 	at com.hmdm.MDMService$RemoteServiceConnection.onServiceConnected(MDMService.java:93)
11-24 14:59:17.045  6660  6660 E AndroidRuntime: 	at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1734)
11-24 14:59:17.045  6660  6660 E AndroidRuntime: 	at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1766)
11-24 14:59:17.045  6660  6660 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:873)
11-24 14:59:17.045  6660  6660 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
11-24 14:59:17.045  6660  6660 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
11-24 14:59:17.045  6660  6660 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6702)
11-24 14:59:17.045  6660  6660 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-24 14:59:17.045  6660  6660 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
11-24 14:59:17.045  6660  6660 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
11-24 14:59:17.051   956  3788 W ActivityManager:   Force finishing activity com.hmdm.apn/.MainActivity
```

**Comment by h-mdm** [comment]
The issue has been fixed, please pull the latest version from the repository.

**Comment by theoneandonly-vector** [comment]
you're so fast :)
seems to work
